connections:
  irtrans:
    it1:
      ip: 10.0.0.117
      port: 21000
      
  ezcontrol:
    ez1:
      ip: 10.0.0.118
      pattern: http://%s/control?cmd=set_state_actuator&number=%s&function=%s
      
# devices/rows/commands
# make sure configured commands are identical to stored ir-database on your irtrans- or ezcontrol-device 

tv_lg_42lm620s:
  type: ir
  label: TV
  powernav: power
  rows:
    00:
      power:
        icon: fa-power-off
        label: Power
      
      vol_up:
        icon: fa-chevron-up
        label: VOL+
      
      vol_down:
        icon: fa-chevron-down
        label: VOL-
      
    
    01:
      prog_up:
        icon: fa-chevron-up
        label: CHANNEL
      
      prog_down:
        icon: fa-chevron-down
        label: CHANNEL
      
    
    0:
      input:
        icon: fa-sign-in
        label: INPUT
      
      tv_radio:
        icon: fa-sign-in
        label: TV/RADIO
      
      home:
        icon: fa-home
        label: Home
      
    
    1:
      emptyspace1: NULL
      arrow_up:
        icon: fa-caret-up
        label: 
      
      emptyspace2: NULL
    
    
    2:
      arrow_left:
        icon: fa-caret-left
        label: 
      
      ok:
        label: OK
      
      arrow_right:
        icon: fa-caret-right
      
    
    
    3:
      emptyspace1: NULL
      arrow_down:
        icon: fa-caret-down
        label: NULL
      
      emptyspace2: NULL
    
    4:
      number1:
        label: 1
      
      number2:
        label: 2
      
      number3:
        label: 3
      
      settings:
        label: SETTINGS
      
    
    5:
      number4:
        label: 4
      
      number5:
        label: 5
      
      number6:
        label: 6
      
      myapps:
        label: MyAPPS
      
    
    6:
      number7:
        label: 7
      
      number8:
        label: 8
      
      number9:
        label: 9
      
      list:
        label: LIST
      
    7:
      back:
        label: BACK
      
      number0:
        label: 0
      
      exit:
        label: EXIT
      
      mute:
        label: MUTE
          
    
    pla:
      stop:
        icon: fa-stop
      
      play:
        icon: fa-play
      
      pause:
        icon: fa-pause
      
      record:
        icon: fa-circle
      
    
    plb:
      rewind:
        icon: fa-backward
      
      ffwd:
        icon: fa-forward
      
      tltxt:
        label: TELETEXT
      
      tltxt_opt:
        label: TLX.OPT
      
    
    5er:
      red:
        label: ROT
      
      green:
        label: GRÜN
      
      yellow:
        label: GELB
      
      blue:
        label: BLAU
      
    
    6er:
      help:
        label: HELP
      
      ratio:
        label: RATIO
    7er:
      quickview:
        label: QUICKVIEW
      
      favorites:
        label: FAVORITES
    8er:
      toggle_3d:
        label: 3D TOGGLE
      
      guide:
        label: GUIDE
    9er:
      quickmenu:
        label: QUICKMENU
      
      info:
        label: INFO
    10er:
      audio_desc:
        label: AUDIO.DESC
      
      app:
        label: APP



beamer_epson_ew3200:
  type: ir
  label: Beamer
  powernav: power
  rows:
    00:
      power:
        icon: fa-power-off
        label: Power
      
      menu:
        icon: fa-bars
        label: MENU
      
      esc:
        #icon: fa-chevron-down
        label: ESC
      

    0:
      src_hdmi1:
        icon: fa-sign-in
        label: HDMI1
      
      src_hdmi2:
        icon: fa-sign-in
        label: HDMI2
      
      src_comp:
        icon: fa-sign-in
        label: COMP
      
    022:
      src_pc:
        icon: fa-sign-in
        label: PC
      
      src_svid:
        icon: fa-sign-in
        label: SVID
      
      src_vid:
        icon: fa-sign-in
        label: VID
      
    1:
      emptyspace1: NULL
      arrow-up:
        icon: fa-caret-up
        label: 
      
      emptyspace2: NULL
    
    
    2:
      arrow-left:
        icon: fa-caret-left
        label: 
      
      enter:
        #icon: MULL
        label: ENTER
      
      arrow-right:
        icon: fa-caret-right
      
    
    
    3:
      emptyspace1: NULL
      down:
        icon: fa-caret-down
        label: NULL
      
      emptyspace2: NULL
    
    4:
      default:
        label: default
      
      memory:
        label: memory
      
      colormode:
        label: colormode
      
    
    5:
      rgbcmy:
        label: rgbcmy
      
      aspect:
        label: aspect
      
      gamma:
        label: gamma
      
    
    6:
      sharpness:
        label: sharpness
      
      pattern:
        label: pattern
      
      blank:
        label: blank
      

    